# Generated by Django 3.2.3 on 2021-06-30 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='req_url',
            new_name='request_url',
        ),
    ]
