# Generated by Django 3.2.3 on 2021-06-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_req_url_project_request_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='request_url',
            field=models.URLField(max_length=100),
        ),
    ]
